version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
      PGPORT: 54320
    expose:
      - '54320'
    ports:
      - '127.0.0.1:54320:54320'
    volumes:
      - ./data:/var/lib/postgresql/data/

  meilisearch:
    image: getmeili/meilisearch:v0.30.5
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=/data.ms
    ports:
      - 7700:7700
    expose:
      - '7700'
    volumes:
      - ./meilisearch/data.ms:/data.ms
    restart: unless-stopped
