apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCl2+BRNVeNzyd7rROD9EyU9kdywYg6bt1ISZxwKPOQ9vNQAwhRq8KSfZmc/4hRRfAmMzfUFUacZtQxJ6fQWD91mQ9JsXb0Znc8dDDiGfjU0VPh9AL82wwLMON6ZF6znIfRGug/BSu5mrn0Lry5kQDYAadwSyuOPW/e3VDnpK4Knl7+g6rOMiu+Cb50QJVykF+k+009GUVHtH/Z4e7x8Fj94Hy4zdAU4S/MzM4nSbNX96/ZpZzQkR1sX5/bUMcrydRI7H7largfavZKK4aXA7rzPIGBrAz+Hz6JAR4iA+tgS0L6v6aUVP60KKQiYhUT8juJ2elL77FFAkOjq6gprGwhdRIEP5sdjnc5Nvh0gY+V7uGPzVZH8x3y7mlH2pn4UtIhv0wN9UagN7iaxeOygi4t7yBTTT114dsXgx7MP2d+XM2j5sza4JZORxKS4sjT9z7AcPvl25aOv5g/Aw1sj+71U4Q28Md/QHgcmEcalZiXJMvZOK7oPaVdmhLHmMEqSGv/AJvYH8/NV0cXCJojgMd8I0gxNPHxFVQZFzuz3aUyJ6NfNMnkcukkjAzOKSGPpIc7XfeYCdZuUW//PGjsfwvhkUemmW0m/YakAY1mtrpMupDLI5wS0qb06sfE9HI6EQULZjunA6Hu4uiTCqIva8a+mjc6hs4v33p1EkC+DBFgjbN94PhZeKR/oqPPesPhBuWgC0QLNzpLphBDliJfUOasi4YJauRw8pZlWd/ekPRY
    POSTGRES_PASSWORD: AgC/zHfEBb7YELZ7lzE7QCmVEnWEeTYWp/gO3RlZEV3wni9DdGdi2SBJGuEgIKAtri5Q0AW8Y0VEHLQ2mwRA5AJUEznhSK8gQnuGG1+Le/U9fiAuHMG0ZRHRmlgTB6jHRxG386KCdP7XnApBQJjUPUoEiWEo5hNDrKZNYh2+wdB6TpZPWvAb5ErnNL0yWI8NoLZcs+byXQ3qjgIZQZ0ZbJEKgFH8caISfyEtC8yaIvWEVBX+Ogc4tDAOjnZfZtOSiYHLJ3IIgCEGJLG+uQdno6of9kDRsfoAxOO+iJc7UjKrnrX74VwN2FXaMoGHrSshLnChdBg093M8hR/49xl+4k9mHLSQBPrYA8Z/5qVclbPpsU4yBMJICQ7YrfLzyO37axApeg7UCY8D+Q04Oh+ArWuzKPUGkaasI7IfwWP5F42Eyy3Xbumbamd9skqm3I8mdWzlXIw4oRjnQxjAwVye/Fho8MS1TrvDJUIEOKnOHrvcLA4+SdW2TInIzZTkGn9pfCBi1ebp8R4Ozvy+d29rNOJxBFYUhZF9ajZs1QqAiPTNNba5wAyG6XxlbBqD+LBVwsoXSw/zKUsy/YQuoRZWNoLmHu/V5L8y02onyaKkPFGC5J4cooplo5OCL60xwBqIarDVv8TM6AC6vAdquaJeDzs4exM8Ka3LJXBPK/aEF6WX1rApEJEVaGJcPjqPlS/2Rfjy2dLoOQnhvlYSnlJKFbjaYIIdSAmHF3zRSbrgdMR5
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-database-secret
      namespace: standalone

