apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBMwW9xAEyLmpzvW49zdML43K7xiUP6WTNqZeeI4I4JMxJWTwoPerZSOHY4PLV5a6IPoiV9+m4HoS+Xvv/AYLuorgTdcXVx5LeGIw6Iscttd83Mvn6jtIE+tRl4C8OFv9JeXS1WFE+fga2UKNhvQTrJhk9AZ3GZtDZHc9l7NF+Awbd1kXcMiFkJb0H+ZG5a9B1oR4hoF7h5LhqFuX1a4fQqfQktPt/G2ZkAanOl9nrK2+twuoaBfqRHROh7FckXreT8lqttO7o5kx5dzeWkC3+WFJxPH8kd7r8LJd0/ugTLlLexJSiabO9kv82duTGLKUgBcpPV8zYlqkMZ4dLCCmUvgEafY+ZZRxyZAd8UxY/1oan2KhjbNP44nQyEzwB8Vnx8PI/RxNoj51UguCYDviwYmiJf1wptTbltLMWDoER/WALQ8yc7x9pATQFIuh+qOBVS2GueBX3iM0d8m7beqXeE/DpakYrecKaRAjT+I7FcY3A+eSYYt6r+U9dW7KrFVSBxKmcUN4k3RorlI5Y6YmmuteWDhySsShfzpLGYqY2Upf53RbXPGIF4N/aHrB88kK3pKjZYvdV2n3MJ+jHrb7GxsdqZ1b2mEo/tfe8aQXOibHxXQjzJfmINA22WvRsNMQNXQztsbekkT0vrYVRhuXG4PmWDdxy1Ar4YmIIz2xyzhFEqldUBMmJ4TBQZzh0H/2OIXxcBcQ3YPb6CpjF8nO/ykZPlt/zJaFeA5Wr3f+HB
    POSTGRES_PASSWORD: AgByh6RGr+P0yxPEkiuJCpk42p7tds/7vkWw9+d4YvmR/c7vQ55i6t9ciEm8z7cAQYoTTtlf+M7ABpdIC9MrL8Pv8resyQO4oTYQ4pSIw/mQB/I475a09ONtpFocsLyta3c8GIK85zVSIUzjZHufcgalx++zmbjtCS/9cUX+zb6kbnP6qAgLRrHBCaZIqZquva50OKuFAjzhKBvYwAiLa4wIPZ9+VEBCnBXEY4dYqIA0TJ+gVkKhn8NyfdsUDGS+gOG/qppvuN+j4mDIvPKjNMK7ScuBV6uZuksDBE8eVloe8DaUWsQNq3ldLcZiBfjX0bDaFvqTu+uoyj7BGof2yDyKDZbINIHTqxczsS/PoloZzsqrTx63rEyLLR3ulK9IK1bKpC+xklRJrWwMg+XkMoQMfAU9r0tEl4zhPw77PjOAOhAUyUuRdkyJR38EoNPgcyrmb6NSA0FX69FuHL5HZa18UiJS0CJK4k0vkGmVaPqNWrOyrlxH00I4FfBC6mhOA6bd2DuAGuRw208Qx6z81gWd0rkSB9ZFFo90XDr2H3c3CvK3owJxdrJLHvXV07c3qYV4hvdfbkykyMfKdjaMC6kMJA+hYx85PQ3ssrYIdJDbm44WTkv00D8fD0beHaOCOfi+uPsaUahixT0VZqKDiSsu6x6p4d5Q+d/jRuBXmwTB3wgRZlaYd248TLBYwA0lOBbcr5Bn3Cae672NU+PAMRPtzR5LiVWfln6uldwA2EWN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-database-secret
      namespace: standalone

