apiVersion: v1
kind: Secret
metadata:
  name: marianum-strapi-database-secret
annotation:
  sealedsecrets.bitnami.com/managed: "true"
data:
  POSTGRES_PASSWORD: OGNDR0VBbmR2dkNPdkhpZjVyNnJEZXVQSmNJTUlBcA==
  DATABASE_PASSWORD: OGNDR0VBbmR2dkNPdkhpZjVyNnJEZXVQSmNJTUlBcA==
