apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBTmo05R+/mdB7gmNlzsIZtiItiapU0gGYMIupMvtMqrxG2sf4HK4jb2RNy66gh1WztR3ta8dH6vy3kbT81kYwelKAVLYwUTyIzCXMGhmRXQw3Iru/6mxQ6v51kEoHDuqtLzWX5+DX28Wz/StzvoW6Ffo9sDLU1r35kmwmi2Bq/VIHxtEIJPwq3Qt8nSHEmgWIH70p88nePKS+djpGktvtgP64p9V6KLvdA8FCehpp6IFENlDFdbTqb3exFf0XVhGkAvuV8/AQjRORfoB09vQufbZ7yQ3zPId2MaNpLOfxV1hTnVBP5GQ6cc76he6wnnidu7NAM5WeIEONfj0gYDyMj9sB7mj3mekqE0j9/5TCY1DL7WnvX0iKVJnqx+Ot0zDOb8fFfHQJY+oPXFoUqi5Bj16K5YIPtike5HfGi01nbaKuiTK/xROGISGwj/7s9VgZI02OQ8VPPlKNErc17s0Yp8hUJXLFyR1kGd1QTV48c6b22IshmXCaRr21jtW8Ul7kGfhF1sA52fQZaqIYsDBpA3Q0dEmRiUxLM0Xkxb6VIO1XvMIisTiZlZYYQ2+mWZnfyOsavrslnRZHiIOz7tt19AA5cButIk/VIS7oBW4i/thqR1Lhk+97bgPKNAqAHK9Fk1jtE+t2ZurNsMfIkNAtRCyctp+ZGAia58XAad32/m1bLN0v1RvwxfNklkJFa+I0j3CmBop8E0LfonGSjxs+4RTtFwddukVAS7SW2Mgtu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-meilisearch-secret
      namespace: standalone

