apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBpasp5A3+hGbkQeNB6Wy1iCAiwfQ8tRrJvIjA3xhsIu+hG5DKrbGWhBOYpsJOQxozQnpt7CC3PvzoiFjUtV9dsv4dMES3DP/e1ZpHKr15r11OliHmZLHZ7IWsih6cNlt5lSQDCUicgQR/56uHRcB6frsscV4lRPmbf9C3JYh1bhJnXkUwgWZg3oehl56xQlIQzUMO3vxv7JwRBNDe8GGj9VBx4OYfpVmLNIbwk6UeUjuxF+npcaghkr2vSquU5gLTPZV2LsJpwJvsSBiyrUl3epcbKuZFLwPf1O1hr52/Hqi/zJeQkyAyEQntgKy9M/Fkm2WnfLnluVYBHOfBPXL+FRSu2GzyPv9KWlIGQO9lklBSKfRdCvDrTp8dueoAMFadeiQMv7CAiguuIy+GZxAJ/NiHeM6a/f0c8uKi507T3U5ZYtBApH1lGJlOtxvqISVYSEr2eaFTYPq5cDolrD9xgvOI77cirkQ5GeDJZuvXflDW5BuwXh9R8pSYBDSOes0/GdkRC33tSWZMPOaUBWqiNyZT45aZXjAJe7tat6O9KS7FbZ27/L2RfNlk4kS6036TrT0E7pFmdn12CLnNgSc4p/ho1CSvQrU1usNr/X3I1743uR2Y2j4WAUpiNx+FndmZ9BiFwYSCKfoX5lHsrcCYagt8/1tKfW25GCywzgWd3hToygDFX8hT4vBb3AYbxnKu1GQc3VD6+rpQDkThadxSSsXadxAaTt+ZxnBVidUgG
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-meilisearch-secret
      namespace: standalone

