apiVersion: v1
kind: Secret
metadata:
  name: marianum-strapi-internals-secret
annotation:
  sealedsecrets.bitnami.com/managed: "true"
data:
  APP_KEYS: WXJtY1ZxZlF5eWJoNVhiZHJacEFIbXZwdmw3cUw4bnRzSnIxZ3NkajJxcz0sWmQyeHV0bVF0cGs2VEMrS09XM3AyMjk5WjhFYlRJYytmMjZwVHJycGkyUT0sQXl2bG0xVWVpaE1SZ3E0RkdOaGVqWG9TS2JXYjlHTHdCZnZRcCtTODA3OD0sOGUzSDA1NzZTNG5XeFVpLzB2bDJtTU82V3FPclN6ejR5VHJIMUc1dlFsdz0=
  ADMIN_JWT_SECRET: SU9nWWxmNUkxMVRIdnhQa29zSjdQc09HdGJicU5xN2dXaFU1Vk8vdDJGTT0=
  API_TOKEN_SALT: WkR3UWZqNDc0aW91UmxWb1Rpa1ZLTnhZamU5MjkzQjlTYmRKaVB5SG5tdz0=
  JWT_SECRET: MzNCLy9aZkFuQTVWVzFEdjc5WTArd1NWdVU0alZ5dEpvSG5ka2JtK2l4Zz0=
