apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBH//nV1AVZmMzYWkqaJteRQ+BiwaFaKyzppwQ8YkoX9u3L5cFYGxQmuN47VMMdE/M4zKTQ3ZVMI2JaIqrzrUiew9cAlVXpRgHpFx5wItmvdRVOUiKI34/IB5XyRMYKNpMOfMgpcq6O/bcU23ObSwvtIT4FStuRVc9lZaHsdaJvL277sGHB5zpUYc24Idx8O7GEor8pYt7kYXnx2nDCIKEXQzFiuGfWzGec7YqFHOhi1cNuq+NOCnhYrKE30mKFSme50Yqy2letLDF7QPM1zkaGzvIbIDA8i/AgWtxQ2P6QszNFbAXSKdZuJztDl4Q1dCuvn0z3ChXKmva+IOz+EqQ08t/1FZXd5OY+a8NGxT+qevjgnGcisdumxWVJQq+JYMRfX58RR83YMYP6zxJ6m05KFZB5v3GyGuca2vkoIbiKb7nHakVIuA0zlIOv8jTVes2g/X+mL9n0pVjaQIm956u4iMt/wW0sXvStQjvtKqhuvsmvbKEZphHsyKiEuyM2JxkMbTTShPvhmgWCNVs3CdqIJyu/ukVuQkdZ5mChwdX0hRp7oW1gZmEZ3PSvAWFeEVWey5gbHoLut7lOmeZzFWLD8bIHWHWsb/5AzJj/VGZzcH0+HN3P5HABTuzNzS3in0Jo0NRkF0Y26WSN2s6bg3cMPsvThak4n03TbNGVc34r0y6lc0cC5MQeU5TeMbAxKLkMGdR8NtlmJ5pCkXPDGcwuKfwLMhJugvg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone
