apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCNdIyRAExQatatw1lK/GL7I212wzrYhLGwTRypuD3x4qpXOBywUTo4YpbAGyG7QZ7bEO39ED5qG8zVKacDJ7ovU44OqToAPq+ZxnvtV67nny6UJpj8Chr/sAUsZvPc9C+GTByl29n0leV1ueYZuRvp1iHHcSFtWPhqT/4e/hJq074wTCPSMbPpom1+WNeW83+I6Rdm22gXVxrBxj1AlkC6M0jRbckClhkenqrrF/U2Q3l11xfMlp1xUGLrwfHYZASJkjZXZUWEqUdu2/WLwS88lnfTsfmDMnAwVHI2PGY+JADbB2xD07TRZqJSYd+hmwCyk+Oh35w6v85C/r36AHSvfsUNG7WkooaNGFbAigauToacU+Io8Yljs/ZLM7iUdv18JRi+yDWjID5MOK7bdvV4972uOE8CWDZG4BKj6Wb1izQ07qnJ42AtEzspyYb2OtAKYybX/VsPh56MGA7ilx8PVR8eYdOrrXyZWG5gNaRp7Lfk+0cfQ6CGHH8XFPiZtru/jzpfZJdY2ROqgUgWLXtvSJV4jb+HmTx7xgN5jy3Sh2QRACpWTWYgF/+l5Zg9vO6Tk+5tWIubfWB+vg2uXzNhxTWpyFov69LH/BtVF1opkmCR482uxNNocLGA+Pxuv/Rjfn+dWQB6t4rDQAHaz6GKi8XTLba6NmuM4lykK6H/T9mEXGEgrGNs3TZvprl3z2plEFWKF59hq/9ie9mdJVA8GGpYxDbmYoc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone
