apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBvSmmCgKLpGXP6VmC55UxC3VZotABZAlWC0FlVI2HcjYHXMwGC16p+B0hBY16CUYsj0eqqHVNaaopkgOkxS8HKkQARzAYHsClz8VWMoOEcrK5P5V+ooakDOZmGgk6uN8oqUe7atgdSWEKj2AzCNbrVlYBpEZplvQHKcVGOL74jtPYy3jflG4DNscHru7RiebIcwGSeYobxt3rcK7ht3pNC6f0kkLBxzBmj5J6dSV4RFjnX564Ab/VOYNOGmMe+/c0u9bOVe/fE52jRbFKdr3rE0QS1S2kBv7NR/zflcjkOjJRrFSfqVSHpJ7gJZaZ0rtbJsSTuc6AEhGHIFePiKPfU6xjdj2hR4lrUr0nxBniXNeFand6vwRA/FdQrvwpEDXnNCBeCWw2EKwhMv5shSx++JizDt1qMUlVWJgfBScbNGmWNyVG3L9Z+Te1hythLIAtARLZu5KjATYlMlTv9ZDdMK4UN+wLMzKRE8sWxNxWewM+0nP893uAal611p4Gphd2WXJnWIv7iTLvDQfowvPbi9LjFhQjFwrinO4NnGbc30ct4N1i6JbQjg5no68Gzv5hFLCYyNv4XPTJJAvB8/Nezdm2mPTESUwSOOUsvnGBRsXe3u+/BFwrlL7f0zynszVwEFdUVGrfbZlZBH50XV8J2EO7LRslS5V1mLpZDmcezsj0x/yntSwZrADxg10KtQIrH7PaYSkVv89xkAy05VKmwi9wwoC2AEkFcxxPRdDdrHyLzALZDML0VR5WMYw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone

