apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCwTBkSkWmfz0Yi5d7fxgxWS24JJinhSdYPvolKo2VtGXPVVRNViFJCRm4nEPe3xyo6hu9hpWHn6NVJdqhdbSlmC0lr6+NrSVfsNGOcSF8Wqkcny3KxmfuTi+dd2fLvvvjrKH/RfmrlhKjBqjJ4EU1ixFD7nFsc7HF/Xi6F7Y42UFt2wWtp9ImEbjn5rLrfoOzfMEEKj2lJc2W7YXOlOPNpX5vBCElJp/3sPhDl0h5iljzjFGf6pvd3IxEq9RG1qhOpCHu+Dw7izCYtdG7PaiIrsbwEbp7DhPrHxMTeHBh8FrZ2aT+6MZgB75ZOsfIyUnoix+IGpxcRTUxhoqfr5elg9kkEq2ZPrZfre5JbFlzxnmBqHaz7kCxgGws+9argUHhMVACREoZBTTrMBB1uKe027GxpJBqlBIqvvquzgoTdvBxRf1URp6duTLsICv+Z7t+p6/qnRyWKy/Sb5SMcYlzMYNOcnXbKGLWW08ttSyQGnheRS9+/ve9Q6IVJN7yLLKfcLVhIAw/HgXlyuY7hYjWes6bsMglx1FKTm/tGa48c82J819pW6Pvy+0g3CCFKs7u17yPBM7caS5NJI0Aa+BheCi5KsaNDigYdGByiZci9R3cfGsawzVIE4AX1Etaq87P1pMf6nS6CdyIigDgzVMSuKDOBN7manoFrdmtIjZnZG56Fn5gsYSPKYGmYVQ1PYK16Lt2sXG92EXzHVOcrfPKdnvjz9cUQsSM=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone
