apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgB469TKL4iuvJHQYDiFmtwgKvAePHiCaZieXinKoy+2sqrVjcrlYX9Wb/FNK/7UquVYIE/itLFB7H2e0bfK9m/Xbr7GtDtbVMnbTTfTuFoamfhTpgbHaLTenYPMyc9coEsDbMokX4xGLzKruWFvbQdcxXQK+zjBe405ciIo5/AWejuW+YC461GX9idD0/uuCxSgbHDNtYmf6zo2JMt2d0gjx/Q/DbYEPnhMvKSsEs4fXDDZhOKgVWuMdiKfew6nTvNZETG+159JGugxRf+LRHq0y5Oy/X0T1MzRBspCPd9oahK2fxzd+7WiNT/tAKAEb4HU+suwPdVIRL/WgoZti3bOaq4zun4tfWakzeMdvXZTQ3SsZ7uIrE7wXy32PPEDfBPyjbqEJcDlRQviimCTqCIztJINIeowXn5cdoopUOVYgddn7OjnuIFyDi6wU47pozTfyVvZkRMPpE5cd96WDDl8DUCvZFKmyFmfOvHl8EK8JFtVB88JSilBFoxQGM4J/gINaZGj0GMnNjnejnqreFYjNaVwSku1epKb6kGaDRJYPhtcq6lPBav2K87IPG4s+fjCh4gJ9p/L/Od6dccP0v3o/rXyYQiN9GyBfOs0XXefJzLxCTEpWn54acfKOHd30XthCTyeg9Y6aUGMnKS3mU7uFqNTghgpOqi0XDRzcdF+vkVMdNn0j9I/0MHfffihQt62ZCoqeNWvoPSdf4kdWFZ6VzJBEbZhloqaFd94+uYRkA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone

