apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBDCOVPbHiDfZ/KhJm5Vmo1CCByZ7sS0MXyQP/GkMyV3j0rdNhY7E23RniCHYQiAm99QnChWbCpPBdMvjb3ZYFUIX9duTm6o64Wg+Jr3O49OD5haG27n3wBDn1w+e2Fv/hShM3gXiRJTwC+JJtUgqqLUfK3d/8MyZiYfc7KJOdJlvTglQPaR/k2HqKvcP335NZIgpwEs4uhWYV6irQNiBuFZUJWYQ58llVRHrZmfEAq0NETk9jKu5vDFY3IqaZzLCyKD8l2Oqjk9n9kfeVhCXCxK5akSZE8iRuiGa71u8fmvuC7ZmZxZ3ROfKI6g4/g6CjEhWRA8jdwJdAMyRu15r4LyzocMSuQdR65v+eA1W4YKxsoZ/XAafzl2FRzSYddVFTa9vZ44IR+KB18AiZJF3DAqt4yElZsUnAe32COfN7hzBIzEhRDYM4HQQql5XCcJ52w15uDKU2bJpcBsMmcQax+7lo/ys1bxePAN8kgrWzDaIy45lti7jT0D4FyRKrkQv9jWooxuGlPP5TGuvcvRwblH41nqJTWB6HllPlluAHfhQCdyGAxjJl3StHMEZ03127g2Z5zRmsgd5o9kEUmHpp00pcYlXFHWqJoPd+XVUwR3ZSlNkjV7CWKrFsrMgR4FaL4QUeWB7WcbB648ahb9QjCThO9obh6mYt4+mm4Ct0OX0zdh9ENk36o5UCCbz04YaTR9tVvXfhnEuryGEltOvGpVkV4AaseyT8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-next-general-secret
      namespace: standalone

